/**
 * UKÁZKOVÁ DATA — jedna akce pro každou z 8 kategorií, plus 2 navíc
 * pro ukázku stavů "Zrušeno" a "Proběhlo".
 *
 * Struktura 1:1 odpovídá tabulce "events" ve schema.sql.
 * photo_url nech prázdné, pokud fotku (zatím) nemáš — karta i detail
 * pak zobrazí hezký barevný placeholder s ikonou kategorie.
 */
window.SAMPLE_EVENTS = [
  {
    id: "evt-1",
    name: "Americano sobota",
    category: "turnaj",
    date: "2026-07-11",
    time_from: "09:00",
    time_to: "13:00",
    location: "Kurty 1–2",
    description_short: "Měnící se dvojice, zábava i pro sólo hráče. Na konci vyhlásíme pořadí.",
    description_long: "Klasické Americano ve skupinách po 4, dvojice se po každém zápase mění. Vhodné i bez parťáka — potkáš se s většinou přítomných hráčů.",
    organizer: "Padel Klatovy",
    phone: "",
    whatsapp: "",
    photo_url: "",
    tags: ["veřejné", "pokročilí", "kapacita omezená"],
    capacity: 16,
    signed_up_count: 9,
    price: 250,
    is_free: false,
    status: "otevreno",
    visibility: "verejne",
    schedule: [
      { time: "09:00", item: "Registrace a rozlosování" },
      { time: "09:30", item: "1. kolo zápasů" },
      { time: "12:30", item: "Vyhlášení pořadí" }
    ],
    what_to_bring: "Vlastní raketu (k zapůjčení na recepci), obuv na antuku/padel"
  },
  {
    id: "evt-2",
    name: "Padel & Gril",
    category: "komunita",
    date: "2026-07-18",
    time_from: "17:00",
    time_to: "21:00",
    location: "Terasa",
    description_short: "Neformální odpoledne s grilem, hudbou a volnými kurty pro všechny.",
    description_long: "Komunitní akce pro členy i jejich rodiny a kamarády. Kurty volně k dispozici, k tomu gril, pití a dobrá nálada na terase.",
    organizer: "Padel Klatovy",
    phone: "",
    whatsapp: "",
    photo_url: "",
    tags: ["zdarma", "veřejné", "grilování", "občerstvení"],
    capacity: 60,
    signed_up_count: 22,
    price: 0,
    is_free: true,
    status: "otevreno",
    visibility: "verejne",
    schedule: [
      { time: "17:00", item: "Otevření terasy a grilu" },
      { time: "18:30", item: "Volná hra na všech kurtech" },
      { time: "20:30", item: "Posezení a hudba" }
    ],
    what_to_bring: "Dobrou náladu, případně vlastní pití na sdílení"
  },
  {
    id: "evt-3",
    name: "Jak se zlepšit v padelu bez nových úderů",
    category: "prednaska",
    date: "2026-07-15",
    time_from: "18:30",
    time_to: "19:30",
    location: "Klubovna",
    description_short: "Taktika, postavení na kurtu a rozhodování – bez jediného nového úderu.",
    description_long: "Přednáška o taktické stránce hry: postavení na kurtu, komunikace s parťákem, výběr úderu podle situace a čtení soupeře.",
    organizer: "Trenér Petr Dvořák",
    phone: "",
    whatsapp: "",
    photo_url: "",
    tags: ["veřejné", "pokročilí", "registrace nutná"],
    capacity: 30,
    signed_up_count: 27,
    price: 0,
    is_free: true,
    status: "posledni_mista",
    visibility: "verejne",
    schedule: [
      { time: "18:30", item: "Úvod a rozdělení témat" },
      { time: "18:45", item: "Postavení na kurtu a taktika" },
      { time: "19:15", item: "Diskuze a dotazy" }
    ],
    what_to_bring: "Poznámkový blok, volitelně raketu na ukázku"
  },
  {
    id: "evt-4",
    name: "První workshop Zdravý hráč",
    category: "zdravy_hrac",
    date: "2026-07-12",
    time_from: "09:00",
    time_to: "10:30",
    location: "Klubovna + kurt 1",
    description_short: "Úvodní lekce prevence zranění a zdravého pohybu na kurtu.",
    description_long: "První workshop cyklu Zdravý hráč: základy správného zahřátí, dechové techniky a prevence nejčastějších padelových zranění.",
    organizer: "Fyzioterapeutka Mgr. Jana Nováková",
    phone: "",
    whatsapp: "",
    photo_url: "",
    tags: ["zdarma", "veřejné", "začátečníci", "kapacita omezená"],
    capacity: 12,
    signed_up_count: 5,
    price: 0,
    is_free: true,
    status: "otevreno",
    visibility: "verejne",
    schedule: [
      { time: "09:00", item: "Teorie: nejčastější zranění" },
      { time: "09:20", item: "Praktické cviky na kurtu" },
      { time: "10:15", item: "Otázky a individuální rady" }
    ],
    what_to_bring: "Sportovní oblečení, pevnou obuv, láhev na pití"
  },
  {
    id: "evt-5",
    name: "Sledování finále Premier Padel na LED obrazovce",
    category: "klubovy_zivot",
    date: "2026-07-25",
    time_from: "19:00",
    time_to: "22:00",
    location: "Terasa (LED obrazovka)",
    description_short: "Společné sledování finále na velké LED obrazovce, s občerstvením.",
    description_long: "Zveme všechny fanoušky padelu na společné sledování finále Premier Padel. Promítáme na venkovní LED obrazovce na terase, zajištěné občerstvení a nápoje.",
    organizer: "Padel Klatovy",
    phone: "",
    whatsapp: "",
    photo_url: "",
    tags: ["zdarma", "veřejné", "občerstvení", "LED obrazovka", "Red Bull"],
    capacity: 80,
    signed_up_count: 14,
    price: 0,
    is_free: true,
    status: "otevreno",
    visibility: "verejne",
    schedule: [
      { time: "19:00", item: "Otevření terasy, občerstvení" },
      { time: "20:00", item: "Přenos finále na LED obrazovce" }
    ],
    what_to_bring: "Nic, jen dobrou náladu"
  },
  {
    id: "evt-6",
    name: "Sportovní teambuilding",
    category: "firemni",
    date: "2026-08-05",
    time_from: "13:00",
    time_to: "17:00",
    location: "Celý areál",
    description_short: "Firemní odpoledne na kurtech – turnaj týmů i pro úplné začátečníky.",
    description_long: "Program na míru pro váš firemní kolektiv: krátký úvod do padelu, rozdělení do týmů a turnaj o drobné ceny. Skvělé pro posílení týmového ducha mimo kancelář.",
    organizer: "PADELUN Consulting (MKD Enterprise, s.r.o.)",
    phone: "",
    whatsapp: "",
    photo_url: "",
    tags: ["pro členy", "začátečníci", "CUPRA", "občerstvení"],
    capacity: 24,
    signed_up_count: 0,
    price: null,
    is_free: false,
    status: "otevreno",
    visibility: "verejne",
    schedule: [
      { time: "13:00", item: "Úvod do padelu" },
      { time: "13:45", item: "Rozdělení do týmů" },
      { time: "14:15", item: "Turnaj týmů" },
      { time: "16:30", item: "Vyhlášení a občerstvení" }
    ],
    what_to_bring: "Sportovní oblečení a obuv, ostatní vybavení zajistíme"
  },
  {
    id: "evt-7",
    name: "Hledáme čtvrtého hráče",
    category: "open_match",
    date: "2026-07-09",
    time_from: "18:00",
    time_to: "19:30",
    location: "Kurt 2",
    description_short: "Chybí nám jeden hráč do sestavy – přidej se a zahraj si s námi.",
    description_long: "Tři hráči mírně pokročilé úrovně mají domluvený kurt a hledají čtvrtého do party. Nezávazné, přátelské tempo, hlavně si užít hru.",
    organizer: "Komunita Padel Klatovy",
    phone: "",
    whatsapp: "",
    photo_url: "",
    tags: ["pro členy", "pokročilí", "kapacita omezená"],
    capacity: 4,
    signed_up_count: 3,
    price: 0,
    is_free: true,
    status: "posledni_mista",
    visibility: "verejne",
    schedule: [],
    what_to_bring: "Raketu, obuv na padel"
  },
  {
    id: "evt-8",
    name: "Večerní skupinový trénink",
    category: "trenink",
    date: "2026-07-14",
    time_from: "19:00",
    time_to: "20:30",
    location: "Kurt 3",
    description_short: "Pravidelný skupinový trénink pod vedením trenéra, max. 8 hráčů.",
    description_long: "Skupinový trénink zaměřený na techniku úderů a herní situace. Skupina je uzavřená na sezónu, kapacita je momentálně naplněná.",
    organizer: "Trenér Petr Dvořák",
    phone: "",
    whatsapp: "",
    photo_url: "",
    tags: ["pro členy", "pokročilí", "registrace nutná"],
    capacity: 8,
    signed_up_count: 8,
    price: 200,
    is_free: false,
    status: "plno",
    visibility: "verejne",
    schedule: [],
    what_to_bring: "Raketu, obuv na padel, ručník"
  },
  {
    id: "evt-9",
    name: "Jarní turnaj dvojic",
    category: "turnaj",
    date: "2026-07-10",
    time_from: "08:30",
    time_to: "18:00",
    location: "Kurty 1–4",
    description_short: "Turnaj byl zrušen kvůli nepříznivé předpovědi počasí.",
    description_long: "Turnaj dvojic v kategoriích open a začátečníci. Bohužel jsme akci museli zrušit kvůli předpovědi silných bouřek. Náhradní termín brzy oznámíme.",
    organizer: "Padel Klatovy",
    phone: "",
    whatsapp: "",
    photo_url: "",
    tags: ["veřejné", "registrace nutná"],
    capacity: 32,
    signed_up_count: 18,
    price: 600,
    is_free: false,
    status: "zruseno",
    visibility: "verejne",
    schedule: [],
    what_to_bring: ""
  },
  {
    id: "evt-10",
    name: "Setkání komunity – jaro",
    category: "komunita",
    date: "2026-05-16",
    time_from: "16:00",
    time_to: "20:00",
    location: "Terasa",
    description_short: "Jarní posezení komunity Padel Klatovy – už proběhlo.",
    description_long: "Jarní komunitní setkání s grilem a volnou hrou. Děkujeme všem, kdo dorazili — fotky najdete na klubovém Facebooku.",
    organizer: "Padel Klatovy",
    phone: "",
    whatsapp: "",
    photo_url: "",
    tags: ["veřejné", "grilování", "občerstvení"],
    capacity: 50,
    signed_up_count: 41,
    price: 0,
    is_free: true,
    status: "probehlo",
    visibility: "verejne",
    schedule: [],
    what_to_bring: ""
  }
];
